### ISSUE TITLE
[Impact Metric Submission]: Average Daily L2 Gas Used per Project

### ISSUE THREAD

**Issue by nutkung1** [opensource-observer/insights#27]
Name of your metric: Average Daily L2 Gas Used per Project
Tags
Optimism Superchain
On-chain Activity
L2 Gas Usage

## Brief description 
This metric calculates the average daily amount of L2 gas used by each project's contracts on the Optimism Superchain. It provides a general indication of the on-chain activity level for each project. Higher average daily L2 gas used suggests potentially more frequent contract interactions or more complex computations happening on-chain.

## SQL code block
Insert the SQL that we should run to replicate your impact metric:
```sql
SELECT project_id, AVG(amount) AS avg_daily_l2_gas_used
FROM `opensource-observer.oso.events_daily_from_project`
WHERE event_type = 'CONTRACT_INVOCATION_DAILY_L2_GAS_USED'
GROUP BY project_id;
```

## Optional: link
Add a link to script/notebook or longer form write-up about the metric:

**Comment by ccerv1** [comment]
* Focus Area: Network Growth
* Query Executes in BigQuery? Yes
* Query Meets Challenge Spec? Yes
* Complexity Score: 🌟
* Utility Score: 🌟
* Total Points: 1
* Comments: Good, clear indicator
