### ISSUE TITLE
[Impact Metric Submission]:  Number of Unique Contributors per Project (Monthly, using 'GITHUB' source)

### ISSUE THREAD

**Issue by nutkung1** [opensource-observer/insights#30]
#  Number of Unique Contributors per Project (Monthly, using 'GITHUB' source)

## Tags
Add one or more keywords to help us categorize your metric. Don't overthink this!
- Optimism Superchain
- Community Engagement
- Developer Activity

## Brief description 
Describe how your impact metric is calculated in 2-3 sentences: This metric identifies projects with a larger pool of contributors on GitHub, potentially indicating broader community interest. It calculates the number of unique addresses that forked the project on GitHub

## SQL code block
Insert the SQL that we should run to replicate your impact metric:
```sql
SELECT
  project_id,
  bucket_month,
  COUNT(DISTINCT from_address) AS unique_github_contributors
FROM `opensource-observer.oso.events_monthly_to_project_by_source`
WHERE event_type = 'FORKED'
  AND from_namespace = 'GITHUB'
GROUP BY project_id, bucket_month
ORDER BY project_id, bucket_month;
```

## Optional: link
Add a link to script/notebook or longer form write-up about the metric:

**Comment by ccerv1** [comment]
* Focus Area: User Growth
* Query Executes in BigQuery? No
* Query Meets Challenge Spec? No
* Complexity Score: -
* Utility Score: -
* Total Points: 0
* Comments: Only considers GitHub data; no onchain component; uses deprecated model
