### ISSUE TITLE
[Impact Metric Submission]: new users for each project within each namespace for each month. 

### ISSUE THREAD

**Issue by nutkung1** [opensource-observer/insights#32]
# new users for each project within each namespace for each month. 

## Tags
Add one or more keywords to help us categorize your metric. Don't overthink this!
- User Engagement
- Active Users

## Brief description 
This metric calculates the total number of new users per project per month across different namespaces. It provides insights into the growth of user base over time and can help in evaluating the effectiveness of user acquisition strategies.

## SQL code block
Insert the SQL that we should run to replicate your impact metric:
```sql
SELECT 
    project_id,
    namespace,
    bucket_month,
    COUNT(*) AS new_user_count
FROM 
    opensource-observer.oso.new_users_monthly_to_project
GROUP BY 
    project_id, namespace, bucket_month
ORDER BY 
    bucket_month DESC, project_id, namespace;
```

## Optional: link
Add a link to script/notebook or longer form write-up about the metric:

**Comment by ccerv1** [comment]
* Focus Area: User Growth
* Query Executes in BigQuery? Yes
* Query Meets Challenge Spec? Yes
* Complexity Score: 🌟
* Utility Score: 🌟
* Total Points: 1
* Comments: Works as described
