### ISSUE TITLE
[Impact Metric Submission]: Total active addresses per project per month

### ISSUE THREAD

**Issue by nutkung1** [opensource-observer/insights#33]
# Total active addresses per project per month

## Tags
Add one or more keywords to help us categorize your metric. Don't overthink this!
- Community Engagement
- Active address

## Brief description 
Describe how your impact metric is calculated in 2-3 sentences: The impact metric calculates the total number of active addresses associated with new users who have engaged with a project within a given month. It aggregates this data by project and month, providing insights into the growth and activity levels of new users over time. This metric helps assess the project's ability to attract and retain users, which is crucial for evaluating its impact and potential long-term sustainability.

## SQL code block
Insert the SQL that we should run to replicate your impact metric:
```sql
SELECT 
    p.project_id,
    m.bucket_month,
    COUNT(DISTINCT m.from_id) AS total_active_addresses
FROM 
    opensource-observer.oso.new_users_monthly_to_project m
JOIN 
    opensource-observer.oso.repository_metrics_by_project p
ON 
    m.project_id = p.project_id
GROUP BY 
    p.project_id,
    m.bucket_month
```

## Optional: link
Add a link to script/notebook or longer form write-up about the metric:

**Comment by ccerv1** [comment]
* Focus Area: User Growth
* Query Executes in BigQuery? Yes
* Query Meets Challenge Spec? No
* Complexity Score: -
* Utility Score: -
* Total Points: 0
* Comments: Only captures new users, not all active addresses
