### ISSUE TITLE
[Impact Metric Submission]: Total Sequencer Fees

### ISSUE THREAD

**Issue by nutkung1** [opensource-observer/insights#34]
# Total Sequencer Fees

## Tags
Add one or more keywords to help us categorize your metric. Don't overthink this!
- Sequencer Fees
- Project Analysis

## Brief description 
Describe how your impact metric is calculated in 2-3 sentences: This SQL query calculates the total sequencer fees grouped by project ID and date from a specified table in the opensource-observer.oso dataset. It filters the data for event types related to sequencer fees and aggregates the amounts accordingly.

## SQL code block
Insert the SQL that we should run to replicate your impact metric:
```sql
SELECT
    project_id,
    DATE(bucket_day) AS date,
    SUM(amount) AS total_sequencer_fees
FROM
    `opensource-observer.oso.events_daily_from_project`
GROUP BY
    project_id,
    date;
```

## Optional: link
Add a link to script/notebook or longer form write-up about the metric:

**Comment by ccerv1** [comment]
* Focus Area: Network Growth
* Query Executes in BigQuery? Yes
* Query Meets Challenge Spec? No
* Complexity Score: -
* Utility Score: -
* Total Points: 0
* Comments: Does not filter on event_type
