### ISSUE TITLE
[Impact Metric Submission]: Assets Remaining on L2s Monthly

### ISSUE THREAD

**Issue by nutkung1** [opensource-observer/insights#36]
# Assets Remaining on L2s Monthly

## Tags
Add one or more keywords to help us categorize your metric. Don't overthink this!
- Finance
- Data Analysis
- Layer 2 solutions (L2s)

## Brief description 
Describe how your impact metric is calculated in 2-3 sentences: This metric calculates the total amount of assets remaining on Layer 2 solutions (L2s) for each project on a monthly basis. It sums up the amount of assets recorded in the events_monthly_to_project table and groups them by project ID and month.

## SQL code block
Insert the SQL that we should run to replicate your impact metric:
```sql
SELECT
    project_id,
    FORMAT_TIMESTAMP('%Y-%m', bucket_month) AS month,
    SUM(amount) AS assets_remaining_on_l2s
FROM
    `opensource-observer.oso.events_monthly_to_project`

GROUP BY
    project_id,
    month;
```

## Optional: link
Add a link to script/notebook or longer form write-up about the metric:

**Comment by ccerv1** [comment]
* Focus Area: Network Growth
* Query Executes in BigQuery? Yes
* Query Meets Challenge Spec? No
* Complexity Score: 
* Utility Score: 
* Total Points: 
* Comments: Sums amounts, but these do not correspond to assets
