### ISSUE TITLE
[Impact Metric Submission]: Number of Farcaster users per month

### ISSUE THREAD

**Issue by BenraouaneSoufiane** [opensource-observer/insights#37]
# Number of Farcaster users per month

## Tags
- farcaster
- optimistic

## Brief description 
This IM calculated from farcaster subproject from the profile database, where the number of rows explain the total users,  I count them & classify the registration date by months, order them to be humain-readable, it explain also the total txs per month beacuse each farcaster registration invoke new transaction from the user address to farcaster IdRegistry address on th OP mainnet
## SQL code block
```
SELECT count(*) as number_of_users,
DATE (TIMESTAMP_TRUNC(last_updated_at, MONTH)) AS months
FROM `opensource-observer.farcaster.profiles`
GROUP BY months ORDER BY months ASC
```

**Comment by ccerv1** [comment]
* Focus Area: User Growth
* Query Executes in BigQuery? Yes
* Query Meets Challenge Spec? Yes
* Complexity Score: 🌟
* Utility Score: 🌟
* Total Points: 1
* Comments: Simple, but works
