### ISSUE TITLE
[Impact Metric Submission]: Pairwise

### ISSUE THREAD

**Issue by jainkrati** [opensource-observer/insights#39]
# Pairwise

## Tags
- voting
- RPGF4

## Brief description 
Pairwise metrics help visualize and analyze voting distribution by different badge holder buckets

## SQL code block
```sql
  -- Sum of votes received by a project in RPGF4 on pairwise by all delegates
  SELECT
    project_id,
    'PAIRWISE_DELEGATE_VOTES' AS impact_metric
  FROM `oso.pairwise`
```

## Response
```json
[{
    "project_id": "jUda1pi-FdNlaUmgKq51B4h8x4wX3QTN2fZkKq6N0vw\u003d",
    "impact_metric": "PAIRWISE_DELEGATE_VOTES",
    "amount": "30"
  }, {
    "project_id": "wdBmT3yweChtV4g4qcc1NN1QtfnmMPAuCVxoPkiAowY\u003d",
    "impact_metric": "PAIRWISE_DELEGATE_VOTES",
    "amount": "120"
  }, {
    "project_id": "HNv9-2g63oZCrLD2jDAIygVq7vQkn2iV2QGmEfcFsYk\u003d",
    "impact_metric": "PAIRWISE_DELEGATE_VOTES",
    "amount": "1500"
  }]
```

## Optional: link
link will soon be shared for the metric apis

**Comment by ccerv1** [comment]
Thank you! Excited to see the API and play around with it. How do you identify projects?

**Comment by jainkrati** [comment]
thanks for your question. We are finishing the api this week and would share asap for you to play around with it.

**Comment by ccerv1** [comment]
Hi @jainkrati I know we been in touch on Discord about the Pairwise integration. I'm very excited to see it! I'm going to close this issue out and when it's ready let's set up a call / demo! Feel free to message me on Discord.

**Comment by jainkrati** [comment]
Thanks for your active engagement and coordination :)
