### ISSUE TITLE
[Trivial] How can we add our project to the observer?

### ISSUE THREAD

**Issue by taempark** [opensource-observer/insights#5]
Hi, this is Taem from Test in Prod.

I'm writing this issue to ask you all how we can add our project to the observer.

I found the list on the [rPGF voting page](https://vote.optimism.io/retropgf/3/list/0x3ce7146c4cead5392c2ae106b501609bdf72ef38e66a6f2ec464ad35ce495614), and seems [one of our repository](https://github.com/testinprod-io/op-erigon) is not on the list though it has 69 stars and applied for [rPGF round 3](https://vote.optimism.io/retropgf/3/application/0x5b7aaf6e99943b8c00ccc443cbfcbeb36858858a7b17abaa9c1e82afe2860895).

Please let me know how to add ourselves to the observer.

Thank you for your work for OSS and public goods. I think it's going to be very helpful for the Collective :)

**Comment by ccerv1** [comment]
Hi Taem! Thanks for your message. The issue with this specific repo is that it originates from a fork. We have a default policy to exclude activity from forked repos. However, let me open an issue with the team to figure out how we should handle these kinds of cases. Keep up the great work ✌️

**Comment by ccerv1** [comment]
Closing this issue here but tracking it on our primary project board
